AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  svls
  Sample SAM Template for svls

Parameters:
  Email:
    Type: String
    Description: The email address to receive notifications
  BucketName:
    Type: String
    Description: The S3 Bucket name

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Architectures:
      - x86_64

  Api:
    MethodSettings:
      - HttpMethod: '*'
        ResourcePath: /*
        DataTraceEnabled: true
        LoggingLevel: INFO

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Connectors:
      DownstreamFunction:
        Properties:
          Destination:
            Id: DownstreamFunction
          Permissions:
            - Write
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      Environment:
        Variables:
          DOWNSTREAM_FUNCTION_NAME: !Ref DownstreamFunction
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  DownstreamFunction:
    Type: AWS::Serverless::Function
    Connectors:
      GetImageConnector:
        Properties:
          Destination:
            - Id: OutPutBucket
            - Id: NotificationTopic
          Permissions:
            - Write
    Properties:
      Environment:
        Variables:
          BUCKET_NAME: !Ref OutPutBucket
          SNS_TOPIC_ARN: !Ref NotificationTopic
      CodeUri: downstream/
      Handler: app.lambda_handler
      Runtime: python3.13

  OutPutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled

  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref Email
          Protocol: email-json

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn